version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "bash", "-c", "/usr/local/bin/init.sh"]
    volumes:
      - "./news_backend/:/usr/src/app/"
    env_file: 
      - ./news_backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./news_backend/.env

  redis:
    image: redis
    container_name: redis

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A news_backend worker --loglevel=info
    env_file: 
      - ./news_backend/.env
    environment:
     - REDIS_URL
     - BROKER_URL
    volumes:
      - "./news_backend/:/usr/src/app/"
    depends_on:
      - db
      - redis

  celery-beat:
    container_name: celery-beat
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A news_backend beat --loglevel=info
    volumes:
      - "./news_backend/:/usr/src/app/"
    env_file: 
      - ./news_backend/.env
    environment:
     - REDIS_URL
     - BROKER_URL
    depends_on:
      - db
      - redis
