openapi: 3.0.3
info:
  title: News Api
  version: 1.0.0
  description: News from the News API,
paths:
  /api/category/:
    get:
      operationId: category_retrieve
      description: Retourne la liste de tout les Regions
      tags:
      - category
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
          description: ''
components:
  schemas:
    News:
      type: object
      description: Serializer Django REST Framework for the news model
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
        author:
          type: string
          nullable: true
          maxLength: 100
        description:
          type: string
          nullable: true
        content:
          type: string
          nullable: true
        url:
          type: string
          format: uri
          maxLength: 3000
        url_to_image:
          type: string
          format: uri
          nullable: true
          maxLength: 3000
        published_at:
          type: string
          format: date-time
          readOnly: true
        category:
          type: string
          maxLength: 50
        country:
          type: string
          maxLength: 50
        source:
          type: string
          nullable: true
          maxLength: 100
      required:
      - category
      - id
      - published_at
      - title
      - url
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
