# Generated by Django 4.2.11 on 2024-03-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Author')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('url', models.URLField(max_length=3000)),
                ('url_to_image', models.URLField(blank=True, max_length=3000, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Source')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
