# Generated by Django 5.0.3 on 2024-03-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_news_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsArticle',
        ),
    ]
