# Generated by Django 5.0.3 on 2024-03-19 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_rename_news_newsarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='image',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='url_to_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
