# Generated by Django 5.0.3 on 2024-03-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_newsarticle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url_to_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
