# Generated by Django 5.0.3 on 2024-03-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_alter_newsarticle_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
    ]
