# Generated by Django 5.0.3 on 2024-03-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_alter_newsarticle_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.TextField(unique=True, verbose_name='Title'),
        ),
    ]
