# Generated by Django 5.0.3 on 2024-03-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_alter_newsarticle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
