# Generated by Django 5.0.3 on 2024-03-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0011_alter_newsarticle_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url_to_image',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
