# Generated by Django 5.0.3 on 2024-03-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0013_newsarticle_unique_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='unique_identifier',
        ),
    ]
