# Generated by Django 5.0.3 on 2024-03-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0014_remove_newsarticle_unique_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='content',
            new_name='urlcontent',
        ),
    ]
