# Generated by Django 5.0.3 on 2024-03-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0015_rename_content_newsarticle_urlcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='urlcontent',
            new_name='content',
        ),
    ]
